server:
  port: 9000
spring:
  application:
    name: "api-gateway-server"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lowerCaseServiceId: true
      httpclient:
        connect-timeout: 1000
        response-timeout: 2s

    config:
      enabled: false
      import-check:
        enabled=false:
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
  info:
    env:
      enabled: true

info:
  app:
    name: "api-gateway-server"
    description: "BMC Gateway Server Application"
    version: "1.0.0"

logging:
  level:
    com:
      bmc:
        api-gateway-server: DEBUG

resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 2
      failureRateThreshold: 50
      waitDurationInOpenState: 10000

