# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deploymentName: api-gateway-server-deployment
serviceName: api-loadbalancer-server
appLabel: api-loadbalancer-server
appName: api-loadbalancer-server

replicaCount: 1

image:
  repository: umeshsingh123/api-loadbalancer-server
  tag: s4

containerPort: 8761

service:
  type: NodePort
  port: 8761
  targetPort: 8761
