# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deploymentName: show-deployment
serviceName: show-service
appLabel: show-service
appName: show-service

replicaCount: 1

image:
  repository: umeshsingh123/show-service
  tag: s4

containerPort: 8083

service:
  type: NodePort
  port: 8083
  targetPort: 8083
